// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kitkecyeofiqaxwktdiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpdGtlY3llb2ZpcWF4d2t0ZGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODI5NjIsImV4cCI6MjA2NTI1ODk2Mn0.-psnwyDetTrYNJV_G5385a7aS09zLlJH0B7DiVUslWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);